month = int(input())
if month == 1: print("January")
elif month == 2: print("February")
elif month == 3: print("March")
elif month == 4: print("April")
elif month == 5: print("")
elif month == 6: print("")
elif month == 7: print("")
elif month == 8: print("")
elif month == 9: print("")
elif month == 10: print("")
elif month == 11: print("")
elif month == 12: print("")